name: CI

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: ['12', '13', '14', '15', '16', '17']

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v10
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: nix-shell --run "nxpg -v ${{ matrix.pg-version }} build"

      - name: Run tests
        run: nix-shell --run "nxpg -v ${{ matrix.pg-version }} test"

  test-on-macos:
    runs-on: macos-13

    strategy:
      matrix:
        pg-version: ['17']

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v10
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: nix-shell --run "nxpg -v ${{ matrix.pg-version }} build"

      - name: Run tests
        run: nix-shell --run "nxpg -v ${{ matrix.pg-version }} test"

  coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        pg-version: ['17']

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v10
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Coverage
        run: nix-shell --run "nxpg -v ${{ matrix.pg-version }} coverage"

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: ./coverage.info
